spring:
  application:
    name: courier-management

  data:
    mongodb:
      uri: mongodb+srv://ritesh:1qaz2wsx3edc4rfv@couriermanagement.0qq1z1f.mongodb.net/courier_db?retryWrites=true&w=majority&appName=courierManagement

jwt:
  secret: Y291cmllcm1hbmFnZW1lbnRzZWNyZXRrZXlmb3Jqd3R0b2tlbmdlbmVyYXRpb24=
  expiration: 86400000
