spring:
  application:
    name: courier-management

  data:
    mongodb:
      uri: mongodb+srv://ritesh:1qaz2wsx3edc4rfv@couriermanagement.0qq1z1f.mongodb.net/courier_db?retryWrites=true&w=majority&appName=courierManagement

  mail:
    host: smtp.gmail.com
    port: 587
    username: accuwu381@gmail.com
    password: ygrkwixxheoeygjq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: Y291cmllcm1hbmFnZW1lbnRzZWNyZXRrZXlmb3Jqd3R0b2tlbmdlbmVyYXRpb24=
  expiration: 86400000
